---
- hosts: bb1
  remote_user: root
  sudo: yes
  gather_facts: no
  vars:
   locale: fr_FR.UTF-8
   timezone: Europe/Paris
   hostname: bb1

  tasks:

    - name: set /etc/hostname
      template: src=./beagletice/hostname dest=/etc/hostname
      tags: hostname

    - name: copy /etc/init.d/led_aging.sh
      copy: src=./beagletice/led_aging.sh dest=/etc/init.d/led_aging.sh owner=root group=root mode=0755

    - name: copy rsa
      copy: src=id_rsa dest=/home/pouchou/id_rsa.conftice owner=root group=root mode=0600
      tags: ssh

    - name: copy wifi interface 
      template: src=./beagletice/wifi dest=/etc/network/interfaces
      tags: ssh

    - name: copy  resolvconf
      template: src=./beagletice/resolvconf dest=/etc/resolv.conf
      tags: resolv 

    - name: mis a jour apt-get update et upgrade 
      command: /usr/bin/apt-get -y dist-upgrade
      tags: apt

    - name: install package
      action: apt pkg={{item}} state=latest update_cache=yes
      with_items:
       - build-essential
       - python-dev
       - python-setuptools
       - python-pip
       - python-smbus
       - ca-certificates
       - tmux
       - ntp
       - git
       - systemd
       - check-mk-agent
      tags: sysnmod

    - name: sed 
      lineinfile: dest=/etc/xinetd.d/check_mk
                regexp='disable'
                line='        disable        = no'
      tags: xinetd

    - name: installation des modules pythons
      action: pip name={{item}} state=latest   
      with_items:
       - Adafruit_BBIO 
       - pytz
       - circus
       - paramiko
       - evdev
      tags: pythonmod

    
    - name: Creation des directory
      file: path={{item}} state=directory
      with_items:
       - /etc/circus
       - /home/bin
      tags: dir

    - name: Deploiement du code Python 
      action: git repo=https://github.com/pushou/beagletice.git dest=/home/bin/beagletice
      tags: codepython

    - name: copy ./beagletice/circus service to /lib/systemd/system/circus.service
      copy: src=./beagletice/circus.service dest=/lib/systemd/system/circus.service
      tags: circus

    - name: copy ./beagletice/circus.ini to /etc/circus
      copy: src=./beagletice/circus.ini dest=/etc/circus/circus.ini
      tags: circus

    - name: systemctl , runlevel3
      command: systemctl enable {{item}}
      with_items:
       - multi-user.target 
       - circus.service
      tags: systemd

    - name: restart circus
      command: systemctl restart circus.service
      notify: update tzdata
      tags: systemd

     

#####################################
   
    - name: gen locale
      copy: src=./beagletice/locale dest=/etc/default/locale
      tags: timezone

    - name: gen locale
      command: /usr/sbin/dpkg-reconfigure --frontend noninteractive locales
      tags: timezone

    - name: set /etc/localtime
      file: src=/usr/share/zoneinfo/{{timezone}} dest=/etc/localtime state=link force=yes
      tags: timezone

    - name: set /etc/timezone
      template: src=./beagletice/template_timezone dest=/etc/timezone
      notify: update tzdata
      tags: timezone

    - name: cron du push vers TICE
      cron: name="push vers TICE"  minute="*/3"   job="/home/bin/beagletice/remonteinfo.py 2>&1 > /dev/null"
      tags: cron

  handlers:
    - name: update tzdata
      command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata
    - name: daemon restart
      command: systemctl --system daemon-reload
