---
- hosts: bb06
  remote_user: root
  sudo: yes
  gather_facts: no

  tasks:

    - name: maj 2 code Python 
      #git: repo=ssh://git@github.com/pushou/beagletice.git dest=/home/pouchou/beagletice accept_hostkey=True 
      git: repo=https://github.com/pushou/beagletice.git dest=/home/pouchou/beagletice  
      tags: codepython

    - name: systemctl restart circus.service
      command: systemctl restart circus.service 
      tags: systemd


